### ISSUE TITLE
Deploy the iotsample job with running failure

### ISSUE THREAD

**Issue by DONGZHUPENG** [microsoft/data-accelerator#81]
After setup Data Accelerator, simply deploy the IoT Sample flow with a new name. 
and several seconds (120s?) later getting below error at jobs tab:

19/06/16 13:56:07 INFO ShutdownHookManager: Shutdown hook called
19/06/16 13:56:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-8dd197f7-3687-4445-93d7-ddb1a1d357ef
19/06/16 13:56:07 INFO MetricsSystemImpl: Stopping azure-file-system metrics system...
19/06/16 13:56:07 INFO MetricsSinkAdapter: azurefs2 thread interrupted.
19/06/16 13:56:07 INFO MetricsSystemImpl: azure-file-system metrics system stopped.
19/06/16 13:56:07 INFO MetricsSystemImpl: azure-file-system metrics system shutdown complete.
stderr:
YARN Diagnostics:
java.lang.Exception: No YARN application is found with tag livy-batch-8-yikjsvds in 120 seconds. Please check your cluster status, it is may be very busy.
org.apache.livy.utils.SparkYarnApp.org$apache$livy$utils$SparkYarnApp$$getAppIdFromTag(SparkYarnApp.scala:182) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:239) org.apache.livy.utils.SparkYarnApp$$anonfun$1$$anonfun$4.apply(SparkYarnApp.scala:236) scala.Option.getOrElse(Option.scala:120) org.apache.livy.utils.SparkYarnApp$$anonfun$1.apply$mcV$sp(SparkYarnApp.scala:236) org.apache.livy.Utils$$anon$1.run(Utils.scala:97)

**Comment by carlbrochu** [comment]
Thanks you for trying Data Accelerator and reporting this issue.  Apologies for running into this issue.  This error usually mean there mismatch in the environment between the configuration and the deployed resources.  We are reviewing the data and will get back to you as soon as possible with more details on how to fix this issue.  Stay tuned.

**Comment by carlbrochu** [comment]
Thanks again for reporting this issue, we are making an update to the template supporting code to avoid this issue in the future.  

To fix this issue in your environment, you will need to update the default job settings.  To do so: 
•	Please go into the Azure portal (http://portal.azure.com), into the subscription you have deployed Data Accelerator, into the Data Accelerator resource group (DataX by default), then into the ‘Azure Cosmos DB account’ instance (name will start with "dx" followed by a number by default or your product name if you have choosen one).  
•	In "Data Explorer", under "Production/commons" you need to edit 2 of the docs named as ‘DataXDirect’ and ‘kafkaDataXDirect’ for the Job configuration JSON so that the documents do not contain “-SNAPSHOT”.  You can remove “-SNAPSHOT” in all of the filenames.   See below for how it should look.
•	Once you do that, then go into the IoT Sample and click deploy to apply the changes to the sample.  You will need to make a change to enable the deploy button, like editing the description or the query).   

for kafkaDataXDirect:
        "file" : "wasbs:///datax/bin/datax-host_2.3_2.11-1.1.0.jar",
            "className" : "datax.app.DirectKafkaStreamingApp",
            "args" : [
                "conf=${sparkJobConfigFilePath}",
                "driverLogLevel=${sparkJobDriverLogLevel}"
            ],
            "jars" : [
                "wasbs:///datax/bin/datax-core_2.3_2.11-1.1.0.jar",
                "wasbs:///datax/bin/datax-utility_2.3_2.11-1.1.0.jar",
                "wasbs:///datax/bin/applicationinsights-core-2.2.1.jar",
                "wasbs:///datax/bin/azure-documentdb-1.16.1.jar",
                "wasbs:///datax/bin/azure-eventhubs-1.2.1.jar",
                "wasbs:///datax/bin/azure-eventhubs-spark_2.11-2.3.6.jar",
                "wasbs:///datax/bin/azure-keyvault-webkey-1.1.jar",
                "wasbs:///datax/bin/datax-keyvault_2.3_2.11-1.1.0-with-dependencies.jar",
                "wasbs:///datax/bin/java-uuid-generator-3.1.5.jar",
                "wasbs:///datax/bin/proton-j-0.31.0.jar",
                "wasbs:///datax/bin/scala-java8-compat_2.11-0.9.0.jar",
                "wasbs:///datax/bin/spark-streaming-kafka-0-10_2.11-2.4.0.jar",
                "wasbs:///datax/bin/kafka-clients-2.0.0.jar"
            ],
for DataXDirect:
            "file" : "wasbs:///datax/bin/datax-host_2.3_2.11-1.1.0.jar",
            "className" : "datax.app.DirectStreamingApp",
            "args" : [
                "conf=${sparkJobConfigFilePath}",
                "driverLogLevel=${sparkJobDriverLogLevel}"
            ],
            "jars" : [
                "wasbs:///datax/bin/datax-core_2.3_2.11-1.1.0.jar",
                "wasbs:///datax/bin/datax-utility_2.3_2.11-1.1.0.jar",
                "wasbs:///datax/bin/applicationinsights-core-2.2.1.jar",
                "wasbs:///datax/bin/azure-documentdb-1.16.1.jar",
                "wasbs:///datax/bin/azure-eventhubs-1.2.1.jar",
                "wasbs:///datax/bin/azure-eventhubs-spark_2.11-2.3.6.jar",
                "wasbs:///datax/bin/azure-keyvault-webkey-1.1.jar",
                "wasbs:///datax/bin/datax-keyvault_2.3_2.11-1.1.0-with-dependencies.jar",
                "wasbs:///datax/bin/java-uuid-generator-3.1.5.jar",
                "wasbs:///datax/bin/proton-j-0.31.0.jar",
                "wasbs:///datax/bin/scala-java8-compat_2.11-0.9.0.jar"
            ],


The definition in Azure Cosmos DB above should match the files deployed in the storage account of the HDInsight cluster.  To see which version is deployed, you can go into the Azure portal (http://portal.azure.com), into the subscription you have deployed Data Accelerator, into the Data Accelerator resource group (DataX by default), then into the storage account (name will start with saspark) under the container defaultdx (folder - /datax/bin/).   These files should match what is configured in Azure Cosmos DB.

Let us know if you run into isues with this or have any other questions.  We look forward to hear back from you.  
Thanks! 
Carl and the Data Accelerator team

**Comment by carlbrochu** [comment]
Hi @DONGZHUPENG were you able to try the solution above?  Since we haven't heard from you in a few days, we'll close this issue as resolved.  Feel free to reopen this one or create a new one if you still run into any problem.  Thanks!

Carl
